name: 09 - Using functions

on:
  workflow_dispatch: 

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR title
        run: echo "${{ github.event.pull_request.title }}"
      - name: Print PR labels
        run: |
          cat << EOF
          ${{ toJSON(github.event.pull_request.labels )}}
          EOF
      - name: Bug step
        if: ${{ !cancelled() && contains(github.event.pull_request.title, 'fix') }}
        run: echo "I am a bugfix"
      - name: I will be skipped
        if: ${{ success() }}
        run: echo "I will print if prvious step succeeded."
      - name: i will execute
        if: ${{ failure() }}
        run: echo "I will prin if any previous steps fails"
      - name: I will execute
        if: ${{ !cancelled() }}
        run: echo "I will always print, ecept when workflow is canceled"
      - name: I will execute when canceled
        if: ${{ cancelled() }}
        run: echo "I will print if the workflow has been canceled"